#!/bin/bash

SCRIPT=$(basename "$1")
shift
PIDDIR=/var/run/libsimple
PIDFILE=/var/run/libsimple/$SCRIPT

if [ ! -d $PIDDIR ]; then
    if [ $UID -ne 0 ]; then
        # for non-root users
        sudo mkdir -p $PIDDIR && sudo chown $USER $LOGDIR
    else
        # for root
        mkdir -p $PIDDIR
    fi
fi

if [ -f $PIDFILE ]; then
  PID=$(cat $PIDFILE)
  ps -p $PID > /dev/null 2>&1
  if [ $? -eq 0 ]; then
    echo "$SCRIPT is already running"
    exit 1
  else
    # Process not found, assume not running
    echo $$ > $PIDFILE
    if [ $? -ne 0 ]; then
      echo "Could not create PID file"
      exit 1
    fi
  fi
else
  echo $$ > $PIDFILE
  if [ $? -ne 0 ]; then
    echo "Could not create PID file"
    exit 1
  fi
fi

# Create a log file for this script.
LOGDIR=/var/log/libsimple
LOGFILE=/var/log/libsimple/$SCRIPT
if [ ! -d $LOGDIR ]; then
    if [ $UID -ne 0 ]; then
        # for non-root users
        sudo mkdir -p $LOGDIR && sudo chown $USER $LOGDIR
    else
        # for root users
        mkdir -p $LOGDIR
    fi
fi
if [ ! -d $LOGFILE ]; then
    touch $LOGFILE
fi

# Run the script and capture its log.
BIN_PATH=$(pwd) # TODO: Don't depend on pwd
echo "Running $SCRIPT (PID: $$)"
source ..env/bin/activate && $BIN_PATH/$SCRIPT "$@" >> $LOGFILE 2>&1

# When it's over, remove the PID file.
rm $PIDFILE
