#!/bin/sh
#
# An example hook script to update the working tree, including its
# submodules, after receiving a push.
#
# To enable this hook, rename this file to "post-receive"
# and run `chmod +x post-receive`.

# Read standard input or hook will fail
while read oldrev newrev refname
do
:
done

# Unset GIT_DIR or the universe will implode
unset GIT_DIR

# This hook requires core.worktree to be explicitly set, and
# receive.denyCurrentBranch to be set to false.
git config --path core.worktree ../
git config --bool receive.denyCurrentBranch false

# Change directory to the working tree; exit on failure
cd `git config --get core.worktree` || exit

# Force checkout
git checkout --force

# Force update submodules
git submodule update --init --recursive --force

# Install the latest version of circulation-web if admin options are set.

if [ -d api/admin ]; then
  cd api/admin
  npm install
  cd ../..
fi

touch --no-dereference uwsgi.ini
