#!/bin/bash

image_branch="$IMAGE_BRANCH"

if [[ -z "$image_branch" ]]; then
  image_branch=`echo "${IMAGE_NAME}" | sed "s/\(nypl\/\)*circ-//"`;
fi

# Clone the right version of the circulation code.
docker build \
  --build-arg version=${SOURCE_BRANCH} \
  -f "Dockerfile.$image_branch" \
  -t ${IMAGE_NAME} \
  --no-cache .
