#!/bin/bash
set -ex

# Clone the right version of the circulation code.
docker build \
  --build-arg version=${SOURCE_BRANCH} \
  -f Dockerfile \
  --target ${IMAGE_BRANCH} \
  -t ${IMAGE_NAME} \
  --no-cache .
