#!/bin/bash

WORKDIR=/var/www/circulation
BINDIR=${WORKDIR}/bin

if [ -d /etc/circulation ] && ! [ -z "$FIRST_RUN" ] && [ -f ${BINDIR}/util/initialize_instance ]; then\
    source ${WORKDIR}/env/bin/activate && ${BINDIR}/util/initialize_instance;\
fi;
